### ISSUE TITLE
Statusline detail setting

### ISSUE THREAD

**Issue by amikai** [wbthomason/lsp-status.nvim#14]
The readme show the example image like this:
![](https://github.com/nvim-lua/lsp-status.nvim/raw/master/images/no_errors.png)

Could you give the full setting about this? thanks.

**Comment by wbthomason** [comment]
Per https://github.com/nvim-lua/lsp-status.nvim#lsp-statusline-segment, all you need to do to get the "default" statusline segment is to call `lsp_status.status()` somewhere in your statusline definition.

**Comment by amikai** [comment]
Does it mean i just do `set statusline=%{LspStatus()}`?

**Comment by wbthomason** [comment]
That will be fine if you (1) don't want anything else in your statusline and (2) have the `LspStatus` function from the example in this repo defined in your config.

**Comment by amikai** [comment]
I got it. Thanks
