### ISSUE TITLE
Is it fine to have an option to remove current function indication?

### ISSUE THREAD

**Issue by VVKot** [wbthomason/lsp-status.nvim#20]
It feels a bit jarring to me, I would rather just have indicators. Does `enabled_current_function` option that defaults to `true` makes sense?

**Comment by wbthomason** [comment]
I'd be happy to merge a PR for this, but I'll note that the statusline component shipped in this plugin is meant as an out-of-the-box default --- for significant customization, you're encouraged to build your own statusline component around the functions this plugin provides.

**Comment by wbthomason** [comment]
@VVKot I unexpectedly had a chance to add this - check out the `current_function` config option. Feel free to re-open if this isn't what you had in mind!
