### ISSUE TITLE
Default symbol for Error and Warnings are not shown using common fonts

### ISSUE THREAD

**Issue by snaggen** [wbthomason/lsp-status.nvim#21]
I have tested to use the default system font for Fedora, JetbrainsMono and JetBrainsMono enhanced with powerline symbols and none of them seems to contain any symbol for UTF-8 F05E and F071 which is the unicode characters that Error and Warning is defaulting to. 
I think that this either should be changed to something that is included in most fonts, or it should be documented which font that is recommended and how to change these symbols to something else.

**Comment by snaggen** [comment]
Ok, seems that font awesome is the way to go.... so in the usage section it would be good to mention that you should make sure to have fontawesome installed. 
Under Fedora that is done using :
`sudo dnf install fontawesome-fonts`

**Comment by wbthomason** [comment]
Do you have suggestions for appropriate substitute defaults? I'd be happy to merge a PR either changing the defaults to something more universally supported or updating the docs to mention that you may need fontawesome to see the default symbols.

For what it's worth, I use JetbrainsMono myself, without fontawesome installed, and see the symbols as expected.

**Comment by snaggen** [comment]
Well, if you do not have fontawesome installed I assume you have some other font that provides these characters. It might be a little tricky to know thought, since the fallbacks happens automatically. But just updating the usage documentation to contain some information about this would probably be sufficient.
