### ISSUE TITLE
lsp-status/messaging.lua:98: attempt to index field 'handlers' (a nil value)

### ISSUE THREAD

**Issue by isvicy** [wbthomason/lsp-status.nvim#22]
```shell
Error detected while processing /Users/aaron/github/dotfiles/neovim/.config/nvim/plugin/lsp.vim:
line   11:
E5113: Error while calling lua chunk: ...acker/start/lsp-status.nvim/lua/lsp-status/messaging.lua:98: attempt to index field 'handlers' (a nil value)
```
just stealing your dotfile in your repo.  Above problems occurs.   Does this a setting problem or problem of lsp-status? 

BTW nvim version is NVIM v0.5.0-828-g0a95549d6

**Comment by wbthomason** [comment]
This is an error in the README; I need to update the example to use `callbacks` rather than `handlers` (this was recently changed in Neovim)

**Comment by wbthomason** [comment]
Wait, actually, I'm wrong about that. What's your `lsp-status` version? The latest version should not have this problem (after d9def2c).

**Comment by wbthomason** [comment]
Also, please make sure your nvim version is built from the latest `master`; you need to have this PR merged: https://github.com/neovim/neovim/pull/12655

**Comment by isvicy** [comment]
upgrade neovim to latest master solved this problem.  thx!
