### ISSUE TITLE
Bad argument to in `util.lua:extract_symbols` with some language servers and a custom statusline

### ISSUE THREAD

**Issue by traxys** [wbthomason/lsp-status.nvim#28]
I'm not really sure what is going on here, I think it's an interaction with multiple plugins but I'm really not sure where does it come from exactly.
With some language servers (it does not seem to be all) I get non-stop the error 
```
Error detected while processing CursorHold Autocommands for "<buffer=1>":
E5108: Error executing lua ...are/nvim/plugged/lsp-status.nvim/lua/lsp-status/util.lua:5: bad a
rgument #1 to 'ipairs' (table expected, got number)
```
I'm using `galaxyline.nvim` for my status bar, meaning that I wrote myself most of the status line, so I'm not sure I've done the best job of it, as I'm not very fluent with the Lua nvim API
So I'm not sure if it's a strange interraction with other plugins or a fault of this one, I hope somebody knows more about this

**Comment by wbthomason** [comment]
Can you give more information about which servers give you this error vs. which do not? Also, can you please make sure you have the latest version of `lsp-status` - a similar error was recently patched.

**Comment by traxys** [comment]
Indeed I though I had update the plugins recently, but after an update it does not happen anymore (for reference it was dockerls, and bashls did not do it)

**Comment by wbthomason** [comment]
It sounds like the problem is solved, then?

**Comment by traxys** [comment]
I think yes, I'll re-open the issue if I encounter another server that causes it
