### ISSUE TITLE
Take buffer number argument in statusline_lsp()

### ISSUE THREAD

**Issue by gegoune** [wbthomason/lsp-status.nvim#33]
Hey, seems like `statusline_lsp()` function does not accept buffer number as an argument which results in statusline in all windows to display information for currently active window. Statusline plugins provide a way to build statusline separately for each window so if `statusline_lsp()` did accept buffer number (and pass it to https://github.com/nvim-lua/lsp-status.nvim/blob/0a272e823e30b55aa559a89baa0d9f3197502e4e/lua/lsp-status/diagnostics.lua#L12 instead of hardcoding 0) it would allow them to display diagnostics independently for each window.

**Comment by wbthomason** [comment]
Done!

**Comment by gegoune** [comment]
@wbthomason I meant to send you that message for a while now. Your attitude towards users of Packer, and whatever other repositories, is the best possible. Amount of effort you are putting in while dealing with bugs, feature request and users is truly astonishing - all this while being very respectful and nice. Neovim community is very lucky to have you. Huge thanks for all your time, contributions, plugins and for being just an amazing human being. All the best to you!

Ah, and thanks for that fix. :)

**Comment by wbthomason** [comment]
Thank you for the kind words!
