### ISSUE TITLE
Question: Status line is not displayed correctly

### ISSUE THREAD

**Issue by nabezokodaikon** [wbthomason/lsp-status.nvim#37]
Status line is not displayed correctly

If you set as below, it will look like the screenshot.
```vim
lua << END
local lsp_status = require('lsp-status')
lsp_status.register_progress()

local nvim_lsp = require('lspconfig')

nvim_lsp.tsserver.setup({
  on_attach = lsp_status.on_attach,
  capabilities = lsp_status.capabilities
})
END

function! LspStatus() abort
    if luaeval('#vim.lsp.buf_get_clients() > 0')
        return luaeval("require('lsp-status').status()")
    endif

    return ''
endfunction

set statusline=%{LspStatus()}
```

<img width="581" alt="スクリーンショット 2021-02-04 21 44 23" src="https://user-images.githubusercontent.com/3197942/106894362-35964b80-6732-11eb-84cf-a08ff4d4ad2a.png">

How do you make it look like a sample?

**Comment by wbthomason** [comment]
Do you have the fonts mentioned in the README installed?

**Comment by ajitid** [comment]
Do we also need to define `handlers = lsp_status.extensions.tsserver.setup()` here?

**Comment by wbthomason** [comment]
@zlksnk: We haven't explicitly implemented any extensions for `tsserver`. If you'd like these to be added, please open a new PR or issue with more information (e.g. what are the extensions, etc.). Thanks!

**Comment by nabezokodaikon** [comment]
I can't have a status line like the sample. I gave up. Thank you.
