### ISSUE TITLE
separator between indicator and count intended?

### ISSUE THREAD

**Issue by dchinmay2** [wbthomason/lsp-status.nvim#56]
![image](https://user-images.githubusercontent.com/36493671/118646035-4cead780-b7fd-11eb-9e87-60b46bae164c.png)

https://github.com/nvim-lua/lsp-status.nvim/blob/7c376c3924d4f807d6ce49450fdeaa18720349c9/lua/lsp-status/statusline.lua#L49

Was this intended? Aren't the separators supposed to be between different types of info?

**Comment by dchinmay2** [comment]
If not, I'll make a PR (but I think it will be messy)

**Comment by wbthomason** [comment]
What font are you using, and do you have customized symbols? I cannot reproduce this visually in my setup - it looks like https://github.com/nvim-lua/lsp-status.nvim/blob/master/images/some_errors.png for me.

**Comment by dchinmay2** [comment]
That screenshot doesn't use separators ._.

**Comment by dchinmay2** [comment]
The separator used is the normal symbol for "or" - the one you get when you press shift+backslash

**Comment by dchinmay2** [comment]
```lua
require "lsp-status".config({
    indicator_separator = "|",
    .......
})
```

**Comment by dchinmay2** [comment]
also, the code snippet i mentioned seems to insert the separator between the indicator and the count

https://github.com/nvim-lua/lsp-status.nvim/blob/7c376c3924d4f807d6ce49450fdeaa18720349c9/lua/lsp-status/statusline.lua#L49

**Comment by wbthomason** [comment]
That screenshot does use separators, but they're whitespace (the default).
> also, the code snippet i mentioned seems to insert the separator between the indicator and the count

Yes - I think this is an issue of poor/ambiguous variable naming. In https://github.com/nvim-lua/lsp-status.nvim/pull/29, where `indicator_separator` was introduced, it's clear that the purpose of the separator is to go between the diagnostic symbol and count (hence why the default is whitespace).

However, your intended use (separating the different diagnostic components) is also reasonable. Right now, we don't have a config var for that separator - we hardcode whitespace: https://github.com/nvim-lua/lsp-status.nvim/blob/7c376c3924d4f807d6ce49450fdeaa18720349c9/lua/lsp-status/statusline.lua#L107

Maybe the solution here is
1. Add a config var for the symbol, defaulting to whitespace, that separates statusline components
2. Rename `indicator_separator` to be clearer
3. Add a notice to the README of this breaking change

What do you think?

**Comment by dchinmay2** [comment]
Make the new one `component_separator` and don't break anyone's config, just make it clear in the README?

**Comment by wbthomason** [comment]
Sure, that works too. I would still like to rename the config variables to be clearer, but that can wait for another PR to group any breaking changes we want to introduce.

**Comment by wbthomason** [comment]
@p00f: can you please try #57 to see if it does what you want? We may need to tweak exactly where `component_separator` gets used - right now, I still hardcode whitespace for the start and end of the set of information blocks, which is (imo) visually nicer but kind of an edge case hack.

**Comment by dchinmay2** [comment]
![image](https://user-images.githubusercontent.com/36493671/118710730-4f205680-b83c-11eb-840f-582e0abc889e.png)

![image](https://user-images.githubusercontent.com/36493671/118710758-59425500-b83c-11eb-9868-a1d09dbd76c3.png)

Nice!

**Comment by p00f** [comment]
Ah I think I understand the original use of `indicator_separator` - putting a colon or a hyphen between the icon and the count
