### ISSUE TITLE
[Documentation] Suggestion integration with other status line plugins?

### ISSUE THREAD

**Issue by nymann** [wbthomason/lsp-status.nvim#7]
Is it worth documenting how to integrate status line with third party plugins such as [vim-airline](https://github.com/vim-airline/vim-airline), [lightline](https://github.com/itchyny/lightline.vim) and a "write it yourself" status line?

Rationale would be that some (a lot?) of people are used to working out of the box status line plugins such as vim-airline, and might be confused to how to integrate it?

But on the other hand, this might be out of the scope of this plugin to provide this (trivial I would assume for more experienced Vim users?) info, let me know what you think. :smile:

**Comment by nymann** [comment]
After additional thought, I think this is a bad idea. The documentation of how to add custom functions to your status line should be documented by the 3rd party plugin provider.
The upkeep of documentation when changes to the 3rd party plugin breaks our documentation alone is too much of a hassle.

**Comment by teto** [comment]
@nymann or anyone if you have a vim-airline working config, I would still be very happy to copy/paste it into my own :)

**Comment by wbthomason** [comment]
I'd also be happy to add such a config to the repo if anyone has one.

@teto: Was the sketch I sent you on Gitter not quite right?

**Comment by dlukes** [comment]
In case it's helpful to anyone, [here's what I ended up doing for airline](https://github.com/dlukes/dotfiles/commit/8feb47aec3a2c7ff78b8efc1e85d9580a99fd6a4).

One tricky bit was that [the default `status_symbol`](https://github.com/nvim-lua/lsp-status.nvim/blob/e1a26944039040bf0f6e7716d19878ec1907f50a/lua/lsp-status.lua#L56) can mess up the width of the statusline (not sure if it's airline's fault or my terminal's, didn't investigate further), which results in broken absolute and relative line numbers *if* you place the lsp-status part *before* airline's Z section, where the line numbers are. So you may need to use a different symbol or place the lsp-status part *after* airline's Z section (or both, as I did in the config linked above).

**Comment by serhez** [comment]
I would love to see some config for lightline! I've been trying myself but I'm not satisfied at all with how I have been able to implement this integration.

**Comment by pyrho** [comment]
@serhez You can take a look at my config over [here](https://github.com/pyrho/rc/blob/master/nvim/conf/50-lightline.vim#L133) for lightline (using the bit provided in the readme) (`LspStatus` being the function defined in the README, put that somewhere too).

Make sure you have a call to `autocmd User LspDiagnosticsChanged call lightline#update()` somewhere in your config for it to update properly.

**Comment by spywhere** [comment]
Just for the future reference, here's my plugin on integrating neovim's LSP diagnostic with lightline:

https://github.com/spywhere/lightline-lsp

**Comment by serhez** [comment]
> Just for the future reference, here's my plugin on integrating neovim's LSP diagnostic with lightline:
> 
> https://github.com/spywhere/lightline-lsp

Thanks for this!
