### ISSUE TITLE
Repeated status line message

### ISSUE THREAD

**Issue by kdheepak** [wbthomason/lsp-status.nvim#76]
I'm getting the following message when using `status_progress` in Lualine:

![Screen Shot 2022-04-25 at 3 07 30 PM](https://user-images.githubusercontent.com/1813121/165175421-23237e18-18d3-48ac-8764-a9e3c3afd8a7.png)

The status line message appears to be displayed twice. This only happens for Lua, and not for Rust, Python etc.

I have just one language server configured though:

```
Language client log: ~/.cache/nvim/lsp.log
 Detected filetype:   lua
 
 1 client(s) attached to this buffer: 
 
 Client: sumneko_lua (id: 1, pid: 86322, bufnr: [1])
 	filetypes:       lua
 	autostart:       true
 	root directory:  ~/gitrepos/dotfiles
 	cmd:             lua-language-server
 
 Configured servers list: ccls, svelte, tsserver, rust_analyzer, vimls, cssls, html, pyright, sumneko_lua, tailwindcss, dockerls
```

Any idea what might be going on here?

**Comment by kdheepak** [comment]
I think this has to do with my configuration (although I don't understand what exactly quite yet).

**Comment by lee-shun** [comment]
Hello! I encountered the exact same problem, could you give me any hint? @kdheepak

**Comment by jyf-111** [comment]
i meet the same, and i try to delete the workspace property. then it becomes correct. @lee-shun 
here is my setting for sumneko_lua, Forgive me for being a rookie, i dont know the reason
```lua
require 'lspconfig'.sumneko_lua.setup {
    capabilities = capabilities,
    on_attach = on_attach,
    cmd = { "lua-language-server" },
    filetypes = { "lua" },
    log_level = 2,
    root_dir = function()
        return vim.fn.getcwd()
    end,
    settings = {
        Lua = {
            runtime = {
                version = "LuaJIT",
                -- path = runtime_path
            },
            diagnostics = {
                globals = { "vim" }
            },
            -- workspace = {
            --     library = vim.api.nvim_get_runtime_file("", true)
            -- },
            telemetry = {
                enable = false
            }
        }
    }
}
```
